# Generated by Django 4.0.5 on 2022-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppypic',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
