# Generated by Django 4.0.5 on 2022-06-04 00:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_pics', '0002_alter_puppypic_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppypic',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='img'),
        ),
    ]
