# Generated by Django 4.0.4 on 2022-05-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_pics', '0002_puppypic_delete_snack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppypic',
            name='img_url',
            field=models.CharField(max_length=20000),
        ),
    ]
