# Generated by Django 4.0.5 on 2022-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_pics', '0003_alter_puppypic_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppypic',
            name='img_url',
        ),
        migrations.AddField(
            model_name='puppypic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
