# Generated by Django 4.0.5 on 2022-07-12 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('puppy_pics', '0009_alter_pet_breed_alter_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppypic',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 21, 23, 4, 755792, tzinfo=utc)),
        ),
    ]
